name       : ranger
version    : 1.7.2
release    : 2
source     :
    - https://github.com/ranger/ranger/archive/v1.7.2.tar.gz : 80917c93396e46272b6de63816d925eb708291a9f7a559d49b24c571ea0eeeb3
license    : GPL-3.0
component  : utils
summary    : A simple, vim-like file manager
description: |
    ranger is a console file manager with VI key bindings. It provides a minimalistic and nice curses interface with a view on the directory hierarchy. It ships with "rifle", a file launcher that is good at automatically finding out which program to use for what file type.
builddeps  :
    - pkgconfig(python)
build      : |
    %python_setup
install    : |
    %python_install
