name       : ranger
version    : 1.7.2
release    : 1
source     :
    - http://nongnu.org/ranger/ranger-stable.tar.gz : 94f6e342daee4445f15db5a7440a11138487c49cc25da0c473bbf1b8978f5b79
license    : GPL-3.0
component  : utils
summary    : A simple, vim-like file manager 
description: |
        ranger is a console file manager with VI key bindings. It provides a minimalistic and nice curses interface with a view on the directory hierarchy. It ships with "rifle", a file launcher that is good at automatically finding out which program to use for what file type.
builddeps  :
    - pkgconfig(python)
build      : |
    %python_setup
install    : |
    %python_install
