name       : ranger
version    : 1.8.1
release    : 3
source     :
    - https://github.com/ranger/ranger/archive/v1.8.1.tar.gz : ab0e32159cde196df4ff14e9c516aaf8ac2db79e3fdee17e59f327d677a96949
license    : GPL-3.0
component  : utils
summary    : A simple, vim-like file manager
description: |
    ranger is a console file manager with VI key bindings. It provides a minimalistic and nice curses interface with a view on the directory hierarchy.
    It ships with "rifle", a file launcher that is good at automatically finding out which program to use for what file type.
build      : |
    %python_setup
install    : |
    %python_install --optimize=1
